### ISSUE TITLE
Android 12 issue

### ISSUE THREAD

**Issue by gercee** [audioburst-labs/AudioburstSDK-Android#1] opened 2022-02-09 07:47 UTC
This exception is thrown for Android 12:

**java.lang.RuntimeException: Unable to create service com.audioburst.player.core.media.MediaService: java.lang.IllegalArgumentException: : Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.**

**Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.**

**Comment by Kamil-H** [comment] 2022-02-15 08:16
Hi @gercee 
Thank you for the report. The issue is now fixed in the newest version of the library.
I'm closing this issue.

**Closed as completed by Kamil-H** 2022-02-15 08:16 UTC
